version: '2'
services:
  healthpoints-postgresql:
    image: postgres:11.3
    # volumes:
    #     - ~/volumes/jhipster/HealthPoints/postgresql/:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=HealthPoints
      - POSTGRES_PASSWORD=
    ports:
      - 5432:5432
